services:
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./api/.env

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      # - .:/app/api
      - /app/api/node_modules
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: ./app/api/src
          ignore:
            - node_modules/
    depends_on:
      - database

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    volumes:
      # - .:/app/ui
      - /app/ui/node_modules
    ports:
      - '5173:5173'
    develop:
      watch:
        - action: sync
          path: ./ui/src
          target: ./app/ui/src
          ignore:
            - node_modules/
    depends_on:
      - database
      - api
